name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: npm install, build and test
        run: |
          npm install
          cd client && npm install

      - name: Test Server
        run: npm run test:server
      
      - name: Test Client
        run: npm run test:client

      
